# Generated by Django 6.0.1 on 2026-01-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_bhit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='blink',
        ),
    ]
