# Generated by Django 6.0.1 on 2026-01-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_book_blink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bisbn',
            field=models.CharField(max_length=50, verbose_name='ISBN'),
        ),
    ]
