# Generated by Django 6.0.1 on 2026-01-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_book_bisbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='bcreated_at',
        ),
    ]
