# Generated by Django 6.0 on 2026-01-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_created_at_book_bcreated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='bisbn',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ISBN'),
        ),
    ]
